# Disable the "core" compose plugins
disablePlugins:
  - lando-compose

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/compose": /home/runner/work/compose/compose

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev
